name: ci

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.*'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          brew install swift-format
          pip install pyright ruff

      - name: Lint
        run: ./scripts/lint.sh

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [macos-15, macos-13]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          brew install ninja
          pip install requests

      - name: Get tag
        run: |
          if [[ ${{ github.event_name }} != 'pull_request' && ${{ github.ref }} != 'refs/heads/master' ]]; then
            echo "tag=${{ github.ref_name }}" >> "$GITHUB_ENV"
          else
            echo "tag=latest" >> "$GITHUB_ENV"
          fi

      - name: Build vanilla edition
        run: |
          python package.py $tag
          mv build/src/Fcitx5Installer.zip .
          rm -rf build

      - name: Build Pinyin edition
        run: |
          python package.py $tag 拼音版 chinese-addons,lua pinyin true
          mv build/src/Fcitx5Installer.zip Fcitx5-Pinyin.zip
          rm -rf build

      - name: Build Rime edition
        run: |
          python package.py $tag 中州韵版 rime rime true
          mv build/src/Fcitx5Installer.zip Fcitx5-Rime.zip
          rm -rf build

      - name: Build Japanese edition
        run: |
          python package.py $tag 日本語版 mozc mozc true
          mv build/src/Fcitx5Installer.zip Fcitx5-Japanese.zip
          rm -rf build

      - name: Upload artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            *.zip

      - name: Release
        if: ${{ (matrix.os == 'macos-15') && (github.event_name != 'pull_request') }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref == 'refs/heads/master' && 'latest' || github.ref_name }}
          prerelease: ${{ github.ref == 'refs/heads/master' }}
          title: ${{ github.ref == 'refs/heads/master' && 'Nightly Build' || github.ref_name }}
          files: |
            Fcitx5Installer.zip
            Fcitx5-Pinyin.zip
            Fcitx5-Rime.zip
            Fcitx5-Japanese.zip

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
